# Generated by Django 4.0.5 on 2022-06-14 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Estudiante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('date_of_birth', models.IntegerField(default=0, max_length=2)),
                ('gender', models.CharField(max_length=1)),
                ('relationship', models.CharField(max_length=10)),
            ],
        ),
    ]
