# Generated by Django 4.0.5 on 2022-06-14 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppCoder', '0002_family_delete_estudiante'),
    ]

    operations = [
        migrations.AlterField(
            model_name='family',
            name='date_of_birth',
            field=models.DateField(),
        ),
    ]
