# Generated by Django 4.0.5 on 2022-06-15 19:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppCoder', '0003_alter_family_date_of_birth'),
    ]

    operations = [
        migrations.RenameField(
            model_name='family',
            old_name='date_of_birth',
            new_name='fechanacimiento',
        ),
        migrations.RenameField(
            model_name='family',
            old_name='gender',
            new_name='genero',
        ),
        migrations.RenameField(
            model_name='family',
            old_name='name',
            new_name='nombre',
        ),
        migrations.RenameField(
            model_name='family',
            old_name='relationship',
            new_name='parentesco',
        ),
    ]
